spring:
  application:
    name: gateway
    port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://gps-tracker-eureka-server.default.svc.cluster.local:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

position-tracker-url: gps-tracker-service.default.svc.cluster.local:8090
